all:
  children:
    ios:
      vars:
        ansible_become: 'true'
        ansible_become_method: enable
        ansible_become_password: ''
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_password: ''
        ansible_user: chradmin

      children:
        davidcox_net_devices:
          hosts:
            chrdavidcox_mdf:
              ansible_host: 172.23.96.23
              
        distribution_net_devices:
          hosts:
            chrpkg_idf1:
              ansible_host: 172.23.96.12
              
        overflow_net_devices:
          hosts:
            chroverflow_mdf:
              ansible_host: 172.23.64.22
              
